name: Upload Test

on: [push]

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make dummy file
        run: echo "test" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: test.txt
